package team.projectpulse.ram.requirement;

public enum RequirementArtifactType {
    GLOSSARY_TERM,
    BUSINESS_PROBLEM,
    BUSINESS_OPPORTUNITY,
    BUSINESS_OBJECTIVE,
    SUCCESS_METRIC,
    VISION_STATEMENT,
    BUSINESS_RISK,
    ASSUMPTION,
    RISK,
    STAKEHOLDER,
    BUSINESS_RULE,
    FUNCTIONAL_REQUIREMENT,
    FEATURE,
    USE_CASE,
    PRECONDITION,
    POSTCONDITION,
    USER_STORY,
    QUALITY_ATTRIBUTE,
    EXTERNAL_INTERFACE_REQUIREMENT,
    CONSTRAINT,
    DATA_REQUIREMENT,
    OTHER
}
